In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
movies = pd.read_csv('//Users//bagades//Desktop//RS//serendipity-sac2018//moviesv2.csv',
                             error_bad_lines=False)

b'Skipping line 19833: expected 8 fields, saw 10\nSkipping line 34143: expected 8 fields, saw 9\nSkipping line 36015: expected 8 fields, saw 10\nSkipping line 37260: expected 8 fields, saw 12\nSkipping line 44379: expected 8 fields, saw 10\nSkipping line 47551: expected 8 fields, saw 10\n'

In [3]:
train_data = pd.read_csv('//Users//bagades//Desktop//RS//serendipity-sac2018//training.csv')
# train_data = pd.read_csv('../Data/serendipity-sac2018/training.csv')

In [4]:
from datetime import datetime
train_data['timestamp'] = train_data['timestamp'].apply(lambda x: datetime.fromtimestamp(x/1000))

In [5]:
train_data['year'] = train_data['timestamp'].apply(lambda x: x.year)
train_data['month'] = train_data['timestamp'].apply(lambda x: x.month)

In [6]:
train_data['weekday'] = train_data['timestamp'].apply(lambda x: x.weekday())

In [7]:
train_filtered = train_data[train_data['year'] > 2015]

In [8]:
train_filtered_movies = train_filtered.merge(movies,how ='left',on = 'movieId')

In [9]:
train_filtered_movies.head()

,userId,movieId,rating,timestamp,year,month,weekday,title,releaseDate,directedBy,starring,imdbId,tmdbId,genres
0,142882,91658,2.5,2018-01-05 21:34:07,2018,1,4,"Girl with the Dragon Tattoo, The (2011)",2011-12-21,David Fincher,"Daniel Craig, Rooney Mara, Christopher Plummer...",1568346.0,65754.0,"Drama,Thriller"
1,142882,4344,1.0,2018-01-05 21:34:06,2018,1,4,Swordfish (2001),2001-06-08,Dominic Sena,"Hugh Jackman, John Travolta, Halle Berry, Don ...",244244.0,9705.0,"Action,Crime,Drama"
2,142882,45720,2.0,2018-01-05 21:34:03,2018,1,4,"Devil Wears Prada, The (2006)",2006-06-30,David Frankel,"Anne Hathaway, Meryl Streep, Adrian Grenier, S...",458352.0,350.0,"Comedy,Drama"
3,142882,4734,2.0,2018-01-05 21:34:01,2018,1,4,Jay and Silent Bob Strike Back (2001),2001-08-24,Kevin Smith,"Jason Mewes, Kevin Smith, Ben Affleck, Jeff An...",261392.0,2294.0,"Adventure,Comedy"
4,142882,91542,2.0,2018-01-05 21:33:57,2018,1,4,Sherlock Holmes: A Game of Shadows (2011),2011-12-16,Guy Ritchie,"Robert Downey Jr., Jude Law, Rachel McAdams, N...",1515091.0,58574.0,"Action,Adventure,Comedy,Crime,Mystery,Thriller"

In [10]:
train_filtered_movies.shape

(4117647, 14)

In [46]:
train_filtered_movies['genres'] = train_filtered_movies['genres'].apply(lambda x: str(x).split(','))
train_filtered_movies['starring'] = train_filtered_movies['starring'].apply(lambda x: str(x).split(','))

In [43]:
train_filtered_movies.head()

,userId,movieId,rating,timestamp,year,month,weekday,title,releaseDate,directedBy,starring,imdbId,tmdbId,genres
0,142882,91658,2.5,2018-01-05 21:34:07,2018,1,4,"Girl with the Dragon Tattoo, The (2011)",2011-12-21,David Fincher,"Daniel Craig, Rooney Mara, Christopher Plummer...",1568346.0,65754.0,"[Drama, Thriller]"
1,142882,4344,1.0,2018-01-05 21:34:06,2018,1,4,Swordfish (2001),2001-06-08,Dominic Sena,"Hugh Jackman, John Travolta, Halle Berry, Don ...",244244.0,9705.0,"[Action, Crime, Drama]"
2,142882,45720,2.0,2018-01-05 21:34:03,2018,1,4,"Devil Wears Prada, The (2006)",2006-06-30,David Frankel,"Anne Hathaway, Meryl Streep, Adrian Grenier, S...",458352.0,350.0,"[Comedy, Drama]"
3,142882,4734,2.0,2018-01-05 21:34:01,2018,1,4,Jay and Silent Bob Strike Back (2001),2001-08-24,Kevin Smith,"Jason Mewes, Kevin Smith, Ben Affleck, Jeff An...",261392.0,2294.0,"[Adventure, Comedy]"
4,142882,91542,2.0,2018-01-05 21:33:57,2018,1,4,Sherlock Holmes: A Game of Shadows (2011),2011-12-16,Guy Ritchie,"Robert Downey Jr., Jude Law, Rachel McAdams, N...",1515091.0,58574.0,"[Action, Adventure, Comedy, Crime, Mystery, Th..."

In [44]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
X = mlb.fit_transform(train_filtered_movies['genres'])

In [45]:
train_filtered_movies.join(pd.DataFrame(X, columns=mlb.classes_))

,userId,movieId,rating,timestamp,year,month,weekday,title,releaseDate,directedBy,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,nan
0,142882,91658,2.5,2018-01-05 21:34:07,2018,1,4,"Girl with the Dragon Tattoo, The (2011)",2011-12-21,David Fincher,...,0,0,0,0,0,0,1,0,0,0
1,142882,4344,1.0,2018-01-05 21:34:06,2018,1,4,Swordfish (2001),2001-06-08,Dominic Sena,...,0,0,0,0,0,0,0,0,0,0
2,142882,45720,2.0,2018-01-05 21:34:03,2018,1,4,"Devil Wears Prada, The (2006)",2006-06-30,David Frankel,...,0,0,0,0,0,0,0,0,0,0
3,142882,4734,2.0,2018-01-05 21:34:01,2018,1,4,Jay and Silent Bob Strike Back (2001),2001-08-24,Kevin Smith,...,0,0,0,0,0,0,0,0,0,0
4,142882,91542,2.0,2018-01-05 21:33:57,2018,1,4,Sherlock Holmes: A Game of Shadows (2011),2011-12-16,Guy Ritchie,...,0,0,0,1,0,0,1,0,0,0
5,142882,4446,1.5,2018-01-05 21:33:55,2018,1,4,Final Fantasy: The Spirits Within (2001),2001-07-11,Hironobu Sakaguchi,...,0,0,0,0,0,1,0,0,0,0
6,142882,3354,2.5,2018-01-05 21:33:52,2018,1,4,Mission to Mars (2000),2000-03-10,Brian De Palma,...,0,0,0,0,0,1,0,0,0,0
7,142882,4701,1.0,2018-01-05 21:33:51,2018,1,4,Rush Hour 2 (2001),2001-08-03,Brett Ratner,...,0,0,0,0,0,0,0,0,0,0
8,142882,31696,0.5,2018-01-05 21:33:49,2018,1,4,Constantine (2005),2005-02-18,Francis Lawrence,...,1,0,0,0,0,0,1,0,0,0
9,142882,97921,2.0,2018-01-05 21:33:45,2018,1,4,Silver Linings Playbook (2012),2012-11-21,David O. Russell,...,0,0,0,0,0,0,0,0,0,0
10,142882,4299,2.0,2018-01-05 21:33:43,2018,1,4,"Knight's Tale, A (2001)",2001-05-11,Brian Helgeland,...,0,0,0,0,1,0,0,0,0,0
11,142882,5388,2.5,2018-01-05 21:33:41,2018,1,4,Insomnia (2002),2002-05-24,Christopher Nolan,...,0,0,0,1,0,0,1,0,0,0
12,142882,3301,2.5,2018-01-05 21:33:33,2018,1,4,"Whole Nine Yards, The (2000)",2000-02-18,Jonathan Lynn,...,0,0,0,0,0,0,0,0,0,0
13,142882,8972,1.0,2018-01-05 21:33:31,2018,1,4,National Treasure (2004),2004-11-08,Jon Turteltaub,...,0,0,0,1,0,0,1,0,0,0
14,142882,8950,3.0,2018-01-05 21:33:28,2018,1,4,The Machinist (2004),2004-01-18,Brad Anderson,...,0,0,0,1,0,0,1,0,0,0
15,142882,85414,1.5,2018-01-05 21:33:26,2018,1,4,Source Code (2011),2011-04-01,Duncan Jones,...,0,0,0,1,0,1,1,0,0,0
16,142851,103339,3.0,2018-01-05 21:33:18,2018,1,4,White House Down (2013),2013-06-28,Roland Emmerich,...,0,1,0,0,0,0,1,0,0,0
17,142882,54272,2.0,2018-01-05 21:33:15,2018,1,4,"Simpsons Movie, The (2007)",2007-07-27,David Silverman,...,0,0,0,0,0,0,0,0,0,0
18,142882,46976,2.0,2018-01-05 21:33:13,2018,1,4,Stranger than Fiction (2006),2006-11-10,Marc Forster,...,0,0,0,0,1,0,0,0,0,0
19,142882,96079,2.5,2018-01-05 21:33:10,2018,1,4,Skyfall (2012),2012-11-09,Sam Mendes,...,0,1,0,0,0,0,1,0,0,0
20,142882,45447,0.5,2018-01-05 21:33:06,2018,1,4,"Da Vinci Code, The (2006)",2006-05-19,Ron Howard,...,0,0,0,1,0,0,1,0,0,0
21,142882,112552,2.5,2018-01-05 21:33:01,2018,1,4,Whiplash (2014),2014-11-13,Damien Chazelle,...,0,0,0,0,0,0,0,0,0,0
22,142882,4638,0.5,2018-01-05 21:32:59,2018,1,4,Jurassic Park III (2001),2001-07-18,Joe Johnston,...,0,0,0,0,0,1,1,0,0,0
23,142882,3624,1.5,2018-01-05 21:32:49,2018,1,4,Shanghai Noon (2000),2000-05-26,Tom Dey,...,0,0,0,0,0,0,0,0,1,0
24,142882,4816,3.5,2018-01-05 21:32:44,2018,1,4,Zoolander (2001),2001-09-28,Ben Stiller,...,0,0,0,0,0,0,0,0,0,0
25,142882,59369,2.5,2018-01-05 21:32:41,2018,1,4,Taken (2008),2009-01-30,Pierre Morel,...,0,0,0,0,0,0,1,0,0,0
26,142882,8464,2.0,2018-01-05 21:32:38,2018,1,4,Super Size Me (2004),2004-05-07,Morgan Spurlock,...,0,0,0,0,0,0,0,0,0,0
27,142882,53125,1.0,2018-01-05 21:32:35,2018,1,4,Pirates of the Caribbean: At World's End (2007),2007-05-25,Gore Verbinski,...,0,0,0,0,0,0,0,0,0,0
28,142882,109374,4.0,2018-01-05 21:32:29,2018,1,4,"Grand Budapest Hotel, The (2014)",2014-03-07,Wes Anderson,...,0,0,0,0,0,0,0,0,0,0
29,142882,122904,3.0,2018-01-05 21:32:27,2018,1,4,Deadpool (2016),2016-02-12,Tim Miller,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4117617,206947,1732,4.0,2016-01-01 00:14:02,2016,1,4,"Big Lebowski, The (1998)",1998-03-06,Joel Coen,...,0,0,0,0,0,0,0,0,0,0
4117618,111908,53519,3.5,2016-01-01 00:12:51,2016,1,4,Death Proof (2007),2007-04-06,Quentin Tarantino,...,1,0,0,0,0,0,1,0,0,0
4117619,160610,143385,4.0,2016-01-01 00:12:51,2016,1,4,Bridge of Spies (2015),2015-10-16,Steven Spielberg,...,0,0,0,0,0,0,1,0,0,0
4117620,194075,140247,3.5,2016-01-01 00:12:30,2016,1,4,The Gift (2015),2015-08-07,Joel Edgerton,...,1,0,0,0,0,0,0,0,0,0
4117621,206947,1884,3.0,2016-01-01 00:12:18,2016,1,4,Fear and Loathing in Las Vegas (1998),1998-05-22,Terry Gilliam,...,0,0,0,0,0,0,0,0,0,0
4117622,106449,2628,3.0,2016-01-01 00:12:09,2016,1,4,Star Wars: Episode I - The Phantom Menace (1999),1999-05-19,George Lucas,...,0,0,0,0,0,1,0,0,0,0
4117623,111908,1089,4.5,2016-01-01 00:10:40,2016,1,4,Reservoir Dogs (1992),1992-01-21,Quentin Tarantino,...,0,0,0,1,0,0,1,0,0,0
4117624,182163,66200,4.5,2016-01-01 00:10:36,2016,1,4,Two Lovers (2008),2009-02-13,James Gray,...,0,0,0,0,1,0,0,0,0,0
4117625,206926,76680,1.5,2016-01-01 00:10:15,2016,1,4,Camille (2007),2007-02-08,Gregory Mackenzie,...,0,0,0,0,1,0,0,0,0,0
4117626,111908,122886,4.5,2016-01-01 00:10:04,2016,1,4,Star Wars: Episode VII - The Force Awakens (2015),2015-12-18,J.J. Abrams,...,0,1,0,0,0,1,0,0,0,0
4117627,106449,1210,3.5,2016-01-01 00:09:40,2016,1,4,Star Wars: Episode VI - Return of the Jedi (1983),1983-05-25,Richard Marquand,...,0,0,0,0,0,1,0,0,0,0
4117628,106449,260,4.0,2016-01-01 00:09:23,2016,1,4,Star Wars: Episode IV - A New Hope (1977),1977-05-25,George Lucas,...,0,0,0,0,0,1,0,0,0,0
4117629,206743,78637,0.5,2016-01-01 00:06:52,2016,1,4,Shrek Forever After (a.k.a. Shrek: The Final C...,2010-05-21,Mike Mitchell,...,0,1,0,0,0,0,0,0,0,0
4117630,103576,134130,5.0,2016-01-01 00:05:50,2016,1,4,The Martian (2015),2015-10-02,Ridley Scott,...,0,0,0,0,0,1,0,0,0,0
4117631,145037,139644,4.0,2016-01-01 00:04:46,2016,1,4,Sicario (2015),2015-09-18,Denis Villeneuve,...,0,0,0,1,0,0,0,0,0,0
4117632,148901,128360,4.0,2016-01-01 00:04:35,2016,1,4,The Hateful Eight (2015),2015-11-13,Quentin Tarantino,...,0,0,0,0,0,0,0,0,1,0
4117633,148901,135875,4.5,2016-01-01 00:04:01,2016,1,4,Queen (2014),2014-02-27,Vikas Bahl,...,0,0,0,0,0,0,0,0,0,0
4117634,148901,134867,3.5,2016-01-01 00:03:39,2016,1,4,Tanu Weds Manu (2011),2011-03-25,Anand L Rai,...,0,0,0,0,1,0,0,0,0,0
4117635,145037,43267,3.5,2016-01-01 00:03:38,2016,1,4,On Probation (Tiempo de Valientes) (2005),2005-09-29,Damián Szifrón,...,0,0,0,0,0,0,0,0,0,0
4117636,145037,57774,3.5,2016-01-01 00:03:31,2016,1,4,"Bottom of the Sea, The (El fondo del mar) (2003)",2003-08-28,Damián Szifron,...,0,0,0,0,0,0,1,0,0,0
4117637,106586,133771,4.5,2016-01-01 00:03:30,2016,1,4,The Lobster (2015),2015-10-16,Yorgos Lanthimos,...,0,0,0,0,1,1,0,0,0,0
4117638,148901,139205,4.0,2016-01-01 00:03:23,2016,1,4,Tanu Weds Manu Returns (2015),2015-05-22,Anand L Rai,...,0,0,0,0,1,0,0,0,0,0
4117639,196067,134130,4.5,2016-01-01 00:03:20,2016,1,4,The Martian (2015),2015-10-02,Ridley Scott,...,0,0,0,0,0,1,0,0,0,0
4117640,148901,115569,4.0,2016-01-01 00:02:59,2016,1,4,Nightcrawler (2014),2014-10-31,Dan Gilroy,...,0,0,0,0,0,0,1,0,0,0
4117641,145037,116897,5.0,2016-01-01 00:02:54,2016,1,4,Wild Tales (2014),2014-08-14,Damián Szifrón,...,0,0,0,0,0,0,1,0,0,0
4117642,106586,106841,4.5,2016-01-01 00:02:48,2016,1,4,August: Osage County (2013),2013-12-25,John Wells,...,0,0,0,0,0,0,0,0,0,0
4117643,106586,89039,4.0,2016-01-01 00:02:24,2016,1,4,Another Earth (2011),2011-07-22,Mike Cahill,...,0,0,0,0,1,1,0,0,0,0
4117644,113071,76093,2.5,2016-01-01 00:01:52,2016,1,4,How to Train Your Dragon (2010),2010-03-26,"Dean DeBlois, Chris Sanders",...,0,1,0,0,0,0,0,0,0,0
4117645,113071,60069,1.0,2016-01-01 00:01:49,2016,1,4,WALL·E (2008),2008-06-27,Andrew Stanton,...,0,0,0,0,1,1,0,0,0,0
4117646,106586,127212,4.0,2016-01-01 00:01:47,2016,1,4,The Stanford Prison Experiment (2015),2015-01-26,Kyle Patrick Alvarez,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
# mlb = MultiLabelBinarizer()
# X1 = mlb.fit_transform(train_filtered_movies['starring'])

In [ ]:
train_filtered_movies.join(pd.DataFrame(X1, columns=mlb.classes_))